version: '3'
services:
  mongodb:
    build: ./mongodb_rs/
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=prisma
      - MONGO_INITDB_DATABASE=crmapi
      - MONGO_REPLICA_HOST=localhost
      - MONGO_REPLICA_PORT=27017
    ports:
      - '27017:27017'